openapi: 3.0.0
info:
  title: My Awesome API
  version: 1.0.0
servers:
  - url: https://my-awesome-api.com
description: The books managing API
paths:
  /api/public/banners:
    get:
      summary: Get all banners
      # parameters:
      #   -in: query
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Banner'
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  /api/public/categories:
    get:
      summary: Get all categories
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
  /api/public/products:
    get:
      summary: Get all products
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'
components:
  schemas:
    Banner:
      type: object
      properties:
        id:
          type: 'string'
          format: 'uuid'
          default: 'generated-uuid-here' # You can replace this with the actual UUID value
          description: 'The unique identifier for the banner'
        link:
          type: 'string'
          description: 'The link associated with the banner'
        name:
          type: 'string'
          description: 'The name of the banner'
        price:
          type: 'integer'
          format: 'int32'
          description: 'The price of the banner'
        startDate:
          type: 'string'
          format: 'date-time'
          description: 'The start date of the banner availability'
        endDate:
          type: 'string'
          format: 'date-time'
          description: 'The end date of the banner availability'
        sellerId:
          type: 'string'
          format: 'uuid'
          description: 'The unique identifier of the seller'
        image:
          type: 'string'
          description: 'The URL or path to the banner image'
        isActive:
          type: 'boolean'
          default: false
          description: 'Indicates whether the banner is currently active'
    Category:
      type: 'object'
      properties:
        id:
          type: 'string'
          format: 'uuid'
          default: 'generated-uuid-here' # Replace with the actual UUID value
          description: 'The unique identifier for the category'
        name_tm:
          type: 'string'
          description: 'The name of the category in Turkmen'
        name_ru:
          type: 'string'
          description: 'The name of the category in Russian'
        name_en:
          type: 'string'
          description: 'The name of the category in English'
        createdAt:
          type: 'string'
          format: 'date-time'
          description: 'The timestamp when the category was created'
        updatedAt:
          type: 'string'
          format: 'date-time'
          description: 'The timestamp when the category was last updated'

    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          format: integer
        message:
          type: string
        errors:
          type: array
          
